#!/usr/bin/env ruby
require 'json'

# TODO: Fail if not found
kernel_spec = {
  argv: [
    Gem.bin_path('iruby', 'iruby'),
    "kernel",
    "{connection_file}",
    Gem.find_latest_files('active_notebook/boot')[0]
  ],
  display_name: "ActiveNotebook",
  language: "ruby"
}

JUPYTER_DATA_DIR = Pathname.new(".jupyter")

JUPYTER_DATA_DIR.join('kernels/active_notebook/kernel.json').tap do |kernel_file|
  kernel_file.parent.mkpath
  kernel_file.write(JSON.pretty_generate(kernel_spec))
end

exec({
  "JUPYTER_DATA_DIR" => JUPYTER_DATA_DIR.to_s
}, 'jupyter lab')

__END__

